services:
  dockge:
    image: louislam/dockge:1.5.0
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
        
      # If you want to use private registries, you need to share the auth file with Dockge:
      # - /root/.docker/:/root/.docker

      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /var/lib/stacks:/var/lib/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/var/lib/stacks
    labels:
      wud.tag.include: ^\d+\.\d+\.\d+$$
      wud.link.template: https://github.com/louislam/dockge/releases/tag/$${major}.$${minor}.$${patch}
      wud.display.name: dockge
